# Site settings
title: DIYbiosphere
email: contact@contact.com
description: "A collaborative directory of Do-it-Yourself Biology initiatives"
baseurl: "" # the subpath of your site, e.g. /blog
url: "sphere.diybio.org"
permalink: /news/:year/:month/:day/:title
repository: "DIYbiosphere/sphere.dir"
github_username: "DIYbiosphere"
twitter:
  username: DIYbiosphere


# Excluded files and dirs
exclude: [script, Gemfile, Gemfile.lock, README.md, DataReusePlan.txt]

# Where things are
source:       .
destination:  ./_site
plugins_dir:  ./_plugins
layouts_dir:  ./_layouts
data_dir:     ./_data
includes_dir: ./_includes

# Build settings
markdown: kramdown

gems:
  - jemoji
  - jekyll-sitemap
  - jekyll-seo-tag

# Collections
collections:
  groups:
    title: Groups
    output: true
    permalink: /groups.html
  projects:
    title: Projects
    output: true
    permalink: /projects/
  labs:
    title: Labs
    output: true
    permalink: /labs/
  startups:
    title: Startups
    output: true
    permalink: /startups/
  incubators:
    title: Incubators
    output: true
    permalink: /incubators/
  networks:
    title: Networks
    output: true
    permalink: /networks/
  events:
    title: Ebents
    output: true
    permalink: /events/
  others:
    title: Others
    output: true
    permalink: /others/

# Defaul Values
defaults:
  -
    scope:
      path: ""
    values:
      layout: landing
  -
    scope:
      type: posts
    values:
      layout: post
  -
    scope:
      type: groups
    values:
      layout: entry
      permalink: /groups/:title
  -
    scope:
      type: projects
    values:
      layout: entry
      permalink: /projects/:title
  -
    scope:
      type: labs
    values:
      layout: entry
      permalink: /labs/:title
  -
    scope:
      type: startups
    values:
      layout: entry
      permalink: /startups/:title
  -
    scope:
      type: incubators
    values:
      layout: entry
      permalink: /incubators/:title
  -
    scope:
      type: networks
    values:
      layout: entry
      permalink: /networks/:title
  -
    scope:
      type: events
    values:
      layout: entry
      permalink: /events/:title
  -
    scope:
      type: others
    values:
      layout: entry
      permalink: /others/:title
